version: '3'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=brew-notifier
      - POSTGRES_USER=brew-notifier
      - POSTGRES_PASSWORD=devpassword
    ports:
      - '5439:5432'
    volumes:
      - ./db.sql:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  notifier-celery:
    image: notifier
    container_name: notifier-celery-server
    entrypoint: ./celery-entrypoint.sh
    depends_on:
      - rabbitmq

  notifier-web:
    image: notifier
    container_name: notifier-django-server
    expose:
      - 8000
    entrypoint: ./django-entrypoint.sh
    links:
      - db
    depends_on:
      - db
      - notifier-celery
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - ./static:/static

    depends_on:
      - notifier-web

volumes:
  db.sql:
    driver: local

networks:
  rabbitmq_net:
    driver: bridge