version: '3'
services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=brew-notifier
      - POSTGRES_PASSWORD=devpassword
    ports:
      - '5439:5432'
    volumes:
      - ./db.sql:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/rabbitmq/data/:/var/lib/rabbitmq/
    networks:
      - rabbitmq_net

volumes:
  db.sql:
    driver: local

networks:
  rabbitmq_net:
    driver: bridge