# Generated by Django 4.0.5 on 2022-06-29 08:47

from django.db import migrations, models
import django.db.models.deletion
import notifier.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('link', models.URLField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('crawling_status', models.CharField(choices=[(0, 'NOT_CRAWLED'), (1, 'ERROR_REQUESTING_LINK'), (2, 'UPDATING_LINK'), (3, 'MARKED_AS_DUPLICATE'), (4, 'UPDATED_LINK'), (5, 'CRAWLING'), (6, 'CRAWLING_FAILED'), (7, 'RESCHEDULED_LONG_CRAWLING'), (8, 'CRAWLING_TOO_LONG'), (9, 'HAS_NO_PAGES'), (10, 'TEXT_UPLOADED'), (11, 'AWAITING_CRAWL'), (12, 'INDEXED_BY_ELASTIC'), (13, 'TEXT_ANALYZED'), (14, 'DOMAIN_INVALID'), (15, 'NO_LINKS_IN_PAGE'), (16, 'UNCRAWLABLE')], max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('last_crawled', models.DateTimeField(default=None, null=True)),
                ('employees_min', models.IntegerField()),
                ('employees_max', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, notifier.models.Entity),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('link', models.URLField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('crawling_status', models.CharField(choices=[(0, 'NOT_CRAWLED'), (1, 'ERROR_REQUESTING_LINK'), (2, 'UPDATING_LINK'), (3, 'MARKED_AS_DUPLICATE'), (4, 'UPDATED_LINK'), (5, 'CRAWLING'), (6, 'CRAWLING_FAILED'), (7, 'RESCHEDULED_LONG_CRAWLING'), (8, 'CRAWLING_TOO_LONG'), (9, 'HAS_NO_PAGES'), (10, 'TEXT_UPLOADED'), (11, 'AWAITING_CRAWL'), (12, 'INDEXED_BY_ELASTIC'), (13, 'TEXT_ANALYZED'), (14, 'DOMAIN_INVALID'), (15, 'NO_LINKS_IN_PAGE'), (16, 'UNCRAWLABLE')], max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('last_crawled', models.DateTimeField(default=None, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, notifier.models.Entity),
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('link', models.URLField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('crawling_status', models.CharField(choices=[(0, 'NOT_CRAWLED'), (1, 'ERROR_REQUESTING_LINK'), (2, 'UPDATING_LINK'), (3, 'MARKED_AS_DUPLICATE'), (4, 'UPDATED_LINK'), (5, 'CRAWLING'), (6, 'CRAWLING_FAILED'), (7, 'RESCHEDULED_LONG_CRAWLING'), (8, 'CRAWLING_TOO_LONG'), (9, 'HAS_NO_PAGES'), (10, 'TEXT_UPLOADED'), (11, 'AWAITING_CRAWL'), (12, 'INDEXED_BY_ELASTIC'), (13, 'TEXT_ANALYZED'), (14, 'DOMAIN_INVALID'), (15, 'NO_LINKS_IN_PAGE'), (16, 'UNCRAWLABLE')], max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('last_crawled', models.DateTimeField(default=None, null=True)),
                ('start_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, notifier.models.Entity),
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('crawling_status', models.CharField(choices=[(0, 'NOT_CRAWLED'), (1, 'ERROR_REQUESTING_LINK'), (2, 'UPDATING_LINK'), (3, 'MARKED_AS_DUPLICATE'), (4, 'UPDATED_LINK'), (5, 'CRAWLING'), (6, 'CRAWLING_FAILED'), (7, 'RESCHEDULED_LONG_CRAWLING'), (8, 'CRAWLING_TOO_LONG'), (9, 'HAS_NO_PAGES'), (10, 'TEXT_UPLOADED'), (11, 'AWAITING_CRAWL'), (12, 'INDEXED_BY_ELASTIC'), (13, 'TEXT_ANALYZED'), (14, 'DOMAIN_INVALID'), (15, 'NO_LINKS_IN_PAGE'), (16, 'UNCRAWLABLE')], max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('last_crawled', models.DateTimeField(default=None, null=True)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('snippet', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.company')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, notifier.models.Entity),
        ),
        migrations.CreateModel(
            name='CompanyForWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.company')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.webinar')),
            ],
            bases=(models.Model, notifier.models.Entity),
        ),
        migrations.CreateModel(
            name='CompanyForEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.company')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.event')),
            ],
            bases=(models.Model, notifier.models.Entity),
        ),
        migrations.CreateModel(
            name='CompanyCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='notifier.company')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor', to='notifier.company')),
            ],
            bases=(models.Model, notifier.models.Entity),
        ),
    ]
