# Generated by Django 4.0.5 on 2022-06-27 13:53

from django.db import migrations, models
import notifier.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('crawling_status', models.CharField(choices=[(0, 'NOT_CRAWLED'), (1, 'ERROR_REQUESTING_LINK'), (2, 'UPDATING_LINK'), (3, 'MARKED_AS_DUPLICATE'), (4, 'UPDATED_LINK'), (5, 'CRAWLING'), (6, 'CRAWLING_FAILED'), (7, 'RESCHEDULED_LONG_CRAWLING'), (8, 'CRAWLING_TOO_LONG'), (9, 'HAS_NO_PAGES'), (10, 'TEXT_UPLOADED'), (11, 'AWAITING_CRAWL'), (12, 'INDEXED_BY_ELASTIC'), (13, 'TEXT_ANALYZED'), (14, 'DOMAIN_INVALID'), (15, 'NO_LINKS_IN_PAGE'), (16, 'UNCRAWLABLE')], max_length=255)),
                ('is_deleted', models.BooleanField()),
                ('is_blacklisted', models.BooleanField()),
                ('last_crawled', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, notifier.models.Entity),
        ),
    ]
