# Generated by Django 4.0.5 on 2022-06-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=None),
            preserve_default=False,
        ),
    ]
