# Generated by Django 4.0.5 on 2022-07-10 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycompetitor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='notifier.company'),
        ),
        migrations.AlterField(
            model_name='companycompetitor',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='notifier.company'),
        ),
        migrations.AlterField(
            model_name='companyforevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notifier.company'),
        ),
        migrations.AlterField(
            model_name='companyforevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notifier.event'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='webinar',
            unique_together={('start_date', 'link')},
        ),
    ]
