# Generated by Django 4.0.5 on 2022-07-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_alter_companycompetitor_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycompetitor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_companies', to='notifier.company'),
        ),
        migrations.AlterField(
            model_name='companyforevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_companies', to='notifier.company'),
        ),
        migrations.AlterField(
            model_name='companyforwebinar',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_companies', to='notifier.company'),
        ),
        migrations.AlterField(
            model_name='companyforwebinar',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_webinars', to='notifier.webinar'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_item_companies', to='notifier.company'),
        ),
    ]
