# Generated by Django 4.0.5 on 2022-07-10 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0003_alter_companycompetitor_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_item_companies', to='notifier.company'),
        ),
    ]
