# Generated by Django 4.0.5 on 2022-06-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0003_alter_event_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_crawled',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
