# Generated by Django 4.0.5 on 2022-06-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0004_alter_event_is_blacklisted_alter_event_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
