# Generated by Django 4.0.5 on 2022-07-10 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0004_alter_contentitem_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyforevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_events', to='notifier.event'),
        ),
    ]
