# Generated by Django 4.0.5 on 2022-06-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0006_company_webinar_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='link',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
